/**
 * This file was auto-generated by scripts/generate-api-schema.mjs.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/vehicles/{vehicleId}/fuel-logs": {
    get: {
      responses: {
        200: { content: {
          "application/json": ({
            id: string;
            vehicleId: string;
            fuelDate: string;
            mileage: number;
            liters: number;
            pricePerLiter: number;
            totalCost: number;
            stationName: string | null;
            isFullTank: boolean;
            consumptionHint: number | null;
            createdAt: string;
          })[];
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    post: {
      requestBody: { content: {
        "application/json": {
          fuelDate: string;
          mileage: number;
          liters: number;
          pricePerLiter: number;
          stationName?: string | null;
          isFullTank?: boolean;
        };
      } };
      responses: {
        201: { content: {
          "application/json": {
            id: string;
            vehicleId: string;
            fuelDate: string;
            mileage: number;
            liters: number;
            pricePerLiter: number;
            totalCost: number;
            stationName: string | null;
            isFullTank: boolean;
            consumptionHint: number | null;
            createdAt: string;
          };
        } };
        400: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
  "/api/vehicles/{vehicleId}/fuel-logs/{id}": {
    get: {
      responses: {
        200: { content: {
          "application/json": {
            id: string;
            vehicleId: string;
            fuelDate: string;
            mileage: number;
            liters: number;
            pricePerLiter: number;
            totalCost: number;
            stationName: string | null;
            isFullTank: boolean;
            consumptionHint: number | null;
            createdAt: string;
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    delete: {
      responses: {
        204: { content: {

        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    patch: {
      requestBody: { content: {
        "application/json": {
          fuelDate?: string;
          mileage?: number;
          liters?: number;
          pricePerLiter?: number;
          stationName?: string | null;
          isFullTank?: boolean;
        };
      } };
      responses: {
        200: { content: {
          "application/json": {
            id: string;
            vehicleId: string;
            fuelDate: string;
            mileage: number;
            liters: number;
            pricePerLiter: number;
            totalCost: number;
            stationName: string | null;
            isFullTank: boolean;
            consumptionHint: number | null;
            createdAt: string;
          };
        } };
        400: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
  "/healthz": {
    get: {
      responses: {
        200: { content: {
          "application/json": {
            status: "ok";
          };
        } };
      };
    };
  };
  "/api/vehicles/{vehicleId}/mileage-readings": {
    get: {
      responses: {
        200: { content: {
          "application/json": ({
            id: string;
            vehicleId: string;
            readingDate: string;
            mileage: number;
            sourceType: string;
            sourceId: string | null;
            note: string | null;
            createdAt: string;
          })[];
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    post: {
      requestBody: { content: {
        "application/json": {
          readingDate: string;
          mileage: number;
          note?: string | null;
        };
      } };
      responses: {
        201: { content: {
          "application/json": {
            id: string;
            vehicleId: string;
            readingDate: string;
            mileage: number;
            sourceType: string;
            sourceId: string | null;
            note: string | null;
            createdAt: string;
          };
        } };
        400: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
  "/api/vehicles/{vehicleId}/mileage-readings/{id}": {
    get: {
      responses: {
        200: { content: {
          "application/json": {
            id: string;
            vehicleId: string;
            readingDate: string;
            mileage: number;
            sourceType: string;
            sourceId: string | null;
            note: string | null;
            createdAt: string;
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    delete: {
      responses: {
        204: { content: {

        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
  "/readyz": {
    get: {
      responses: {
        200: { content: {
          "application/json": {
            status: "ok";
            db: "ok";
          };
        } };
        503: { content: {
          "application/json": {
            status: "error";
            db: "unreachable";
          };
        } };
      };
    };
  };
  "/api/vehicles/{vehicleId}/reminders": {
    get: {
      responses: {
        200: { content: {
          "application/json": ({
            id: string;
            vehicleId: string;
            title: string;
            description: string | null;
            dueDate: string | null;
            dueMileage: number | null;
            status: string;
            dueState: "overdue" | "due_soon" | "ok";
            notifiedAt: string | null;
            createdAt: string;
            updatedAt: string;
          })[];
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    post: {
      requestBody: { content: {
        "application/json": {
          title: string;
          description?: string | null;
          dueDate?: string | null;
          dueMileage?: number | null;
          status: "pending" | "done" | "cancelled";
        };
      } };
      responses: {
        201: { content: {
          "application/json": {
            id: string;
            vehicleId: string;
            title: string;
            description: string | null;
            dueDate: string | null;
            dueMileage: number | null;
            status: string;
            dueState: "overdue" | "due_soon" | "ok";
            notifiedAt: string | null;
            createdAt: string;
            updatedAt: string;
          };
        } };
        400: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
  "/api/vehicles/{vehicleId}/reminders/{id}": {
    get: {
      responses: {
        200: { content: {
          "application/json": {
            id: string;
            vehicleId: string;
            title: string;
            description: string | null;
            dueDate: string | null;
            dueMileage: number | null;
            status: string;
            dueState: "overdue" | "due_soon" | "ok";
            notifiedAt: string | null;
            createdAt: string;
            updatedAt: string;
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    delete: {
      responses: {
        204: { content: {

        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    patch: {
      requestBody: { content: {
        "application/json": {
          title?: string;
          description?: string | null;
          dueDate?: string | null;
          dueMileage?: number | null;
          status?: "pending" | "done" | "cancelled";
        };
      } };
      responses: {
        200: { content: {
          "application/json": {
            id: string;
            vehicleId: string;
            title: string;
            description: string | null;
            dueDate: string | null;
            dueMileage: number | null;
            status: string;
            dueState: "overdue" | "due_soon" | "ok";
            notifiedAt: string | null;
            createdAt: string;
            updatedAt: string;
          };
        } };
        400: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
  "/api/me": {
    get: {
      responses: {
        200: { content: {
          "application/json": {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            localePref: "pl" | "en";
            unitsPref: "metric" | "imperial";
            currencyPref: string;
            createdAt: string;
            updatedAt: string;
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    patch: {
      requestBody: { content: {
        "application/json": {
          firstName?: string;
          lastName?: string;
          localePref?: "pl" | "en";
          unitsPref?: "metric" | "imperial";
          currencyPref?: string;
        };
      } };
      responses: {
        200: { content: {
          "application/json": {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            localePref: "pl" | "en";
            unitsPref: "metric" | "imperial";
            currencyPref: string;
            createdAt: string;
            updatedAt: string;
          };
        } };
        400: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
  "/api/vehicles": {
    get: {
      responses: {
        200: { content: {
          "application/json": ({
            id: string;
            brand: string;
            model: string;
            generation?: string | null;
            productionYear: number;
            engine?: string | null;
            fuelType: "petrol" | "diesel" | "hybrid" | "electric" | "lpg" | "other";
            vin?: string | null;
            registrationNumber?: string | null;
            currentMileage: number;
            currencyCode: string;
            createdAt: string;
            updatedAt: string;
          })[];
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    post: {
      requestBody: { content: {
        "application/json": {
          brand: string;
          model: string;
          generation?: string | null;
          productionYear: number;
          engine?: string | null;
          fuelType: "petrol" | "diesel" | "hybrid" | "electric" | "lpg" | "other";
          vin?: string | null;
          registrationNumber?: string | null;
          currencyCode?: string;
        };
      } };
      responses: {
        201: { content: {
          "application/json": {
            id: string;
            brand: string;
            model: string;
            generation?: string | null;
            productionYear: number;
            engine?: string | null;
            fuelType: "petrol" | "diesel" | "hybrid" | "electric" | "lpg" | "other";
            vin?: string | null;
            registrationNumber?: string | null;
            currentMileage: number;
            currencyCode: string;
            createdAt: string;
            updatedAt: string;
          };
        } };
        400: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        409: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
  "/api/vehicles/{id}": {
    get: {
      responses: {
        200: { content: {
          "application/json": {
            id: string;
            brand: string;
            model: string;
            generation?: string | null;
            productionYear: number;
            engine?: string | null;
            fuelType: "petrol" | "diesel" | "hybrid" | "electric" | "lpg" | "other";
            vin?: string | null;
            registrationNumber?: string | null;
            currentMileage: number;
            currencyCode: string;
            createdAt: string;
            updatedAt: string;
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    delete: {
      responses: {
        204: { content: {

        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    patch: {
      requestBody: { content: {
        "application/json": {
          brand?: string;
          model?: string;
          generation?: string | null;
          productionYear?: number;
          engine?: string | null;
          fuelType?: "petrol" | "diesel" | "hybrid" | "electric" | "lpg" | "other";
          vin?: string | null;
          registrationNumber?: string | null;
          currencyCode?: string;
        };
      } };
      responses: {
        200: { content: {
          "application/json": {
            id: string;
            brand: string;
            model: string;
            generation?: string | null;
            productionYear: number;
            engine?: string | null;
            fuelType: "petrol" | "diesel" | "hybrid" | "electric" | "lpg" | "other";
            vin?: string | null;
            registrationNumber?: string | null;
            currentMileage: number;
            currencyCode: string;
            createdAt: string;
            updatedAt: string;
          };
        } };
        400: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        409: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
}

export interface components {
  "schemas": {

  };
  "parameters": {

  };
}
