/**
 * This file was auto-generated by scripts/generate-api-schema.mjs.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/me/export": {
    get: {
      responses: {
        200: { content: {
          "application/json": {
            exportedAt: string;
            version: 1;
            profile: {
              id: string;
              firstName: string;
              lastName: string;
              email: string;
              localePref: "pl" | "en";
              unitsPref: "metric" | "imperial";
              currencyPref: string;
              createdAt: string;
              updatedAt: string;
            };
            vehicles: ({
              id: string;
              brand: string;
              model: string;
              generation?: string | null;
              productionYear: number;
              engine?: string | null;
              fuelType: "petrol" | "diesel" | "hybrid" | "electric" | "lpg" | "other";
              vin?: string | null;
              registrationNumber?: string | null;
              currentMileage: number;
              currencyCode: string;
              createdAt: string;
              updatedAt: string;
            })[];
            fuelLogs: ({
              id: string;
              vehicleId: string;
              fuelDate: string;
              mileage: number;
              liters: number;
              pricePerLiter: number;
              totalCost: number | null;
              stationName?: string | null;
              isFullTank: boolean;
              createdAt: string;
            })[];
            chargingSessions: ({
              id: string;
              vehicleId: string;
              chargeDate: string;
              mileage: number;
              energyKwh: number;
              pricePerKwh: number;
              totalCost: number | null;
              chargerType: "home_socket" | "ac_type2" | "dc_ccs" | "dc_chademo" | "tesla_sc" | "other";
              socStartPercent?: number | null;
              socEndPercent?: number | null;
              stationName?: string | null;
              isFullCharge: boolean;
              createdAt: string;
            })[];
            mileageReadings: ({
              id: string;
              vehicleId: string;
              readingDate: string;
              mileage: number;
              sourceType: "manual" | "fuel_log" | "service_record" | "charging_session";
              sourceId?: string | null;
              note?: string | null;
              createdAt: string;
              updatedAt: string;
            })[];
            serviceRecords: ({
              id: string;
              vehicleId: string;
              serviceDate: string;
              mileage: number;
              title: string;
              description?: string | null;
              laborCost: number | null;
              totalCost: number | null;
              workshopName?: string | null;
              createdAt: string;
              updatedAt: string;
              parts?: ({
                id: string;
                serviceRecordId: string;
                partId: string;
                name: string;
                manufacturer: string | null;
                partNumber: string | null;
                quantity: number;
                unitPrice: number;
                totalPrice: number | null;
              })[];
            })[];
            issues: ({
              id: string;
              vehicleId: string;
              reportedDate: string;
              resolvedDate?: string | null;
              title: string;
              description?: string | null;
              status: "open" | "in_progress" | "resolved" | "cancelled";
              priority: "low" | "medium" | "high" | "critical";
              relatedServiceRecordId?: string | null;
              createdAt: string;
              updatedAt: string;
            })[];
            expenses: ({
              id: string;
              vehicleId: string;
              category: "fuel" | "electricity" | "service" | "parts" | "insurance" | "inspection" | "other";
              expenseDate: string;
              amount: number | null;
              description?: string | null;
              sourceType: "manual" | "fuel_log" | "service_record" | "charging_session";
              sourceId?: string | null;
              isAutoSynced: boolean;
              createdAt: string;
              updatedAt: string;
            })[];
            reminders: ({
              id: string;
              vehicleId: string;
              title: string;
              description?: string | null;
              dueDate?: string | null;
              dueMileage?: number | null;
              status: "pending" | "done" | "cancelled";
              dueState: string;
              notifiedAt?: string | null;
              createdAt: string;
              updatedAt: string;
            })[];
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
  "/api/me": {
    get: {
      responses: {
        200: { content: {
          "application/json": {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            localePref: "pl" | "en";
            unitsPref: "metric" | "imperial";
            currencyPref: string;
            createdAt: string;
            updatedAt: string;
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    delete: {
      requestBody: { content: {
        "application/json": {
          confirmation: string;
        };
      } };
      responses: {
        204: { content: {

        } };
        400: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    patch: {
      requestBody: { content: {
        "application/json": {
          firstName?: string;
          lastName?: string;
          localePref?: "pl" | "en";
          unitsPref?: "metric" | "imperial";
          currencyPref?: string;
        };
      } };
      responses: {
        200: { content: {
          "application/json": {
            id: string;
            firstName: string;
            lastName: string;
            email: string;
            localePref: "pl" | "en";
            unitsPref: "metric" | "imperial";
            currencyPref: string;
            createdAt: string;
            updatedAt: string;
          };
        } };
        400: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
  "/api/vehicles/{vehicleId}/charging-sessions": {
    get: {
      responses: {
        200: { content: {
          "application/json": ({
            id: string;
            vehicleId: string;
            chargeDate: string;
            mileage: number;
            energyKwh: number;
            pricePerKwh: number;
            totalCost: number;
            chargerType: string;
            socStartPercent: number | null;
            socEndPercent: number | null;
            stationName: string | null;
            isFullCharge: boolean;
            createdAt: string;
          })[];
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    post: {
      requestBody: { content: {
        "application/json": {
          chargeDate: string;
          mileage: number;
          energyKwh: number;
          pricePerKwh: number;
          chargerType: "home_socket" | "ac_type2" | "dc_ccs" | "dc_chademo" | "tesla_sc" | "other";
          socStartPercent?: number | null;
          socEndPercent?: number | null;
          stationName?: string | null;
          isFullCharge?: boolean;
        };
      } };
      responses: {
        201: { content: {
          "application/json": {
            id: string;
            vehicleId: string;
            chargeDate: string;
            mileage: number;
            energyKwh: number;
            pricePerKwh: number;
            totalCost: number;
            chargerType: string;
            socStartPercent: number | null;
            socEndPercent: number | null;
            stationName: string | null;
            isFullCharge: boolean;
            createdAt: string;
          };
        } };
        400: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
  "/api/vehicles/{vehicleId}/charging-sessions/{id}": {
    get: {
      responses: {
        200: { content: {
          "application/json": {
            id: string;
            vehicleId: string;
            chargeDate: string;
            mileage: number;
            energyKwh: number;
            pricePerKwh: number;
            totalCost: number;
            chargerType: string;
            socStartPercent: number | null;
            socEndPercent: number | null;
            stationName: string | null;
            isFullCharge: boolean;
            createdAt: string;
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    delete: {
      responses: {
        204: { content: {

        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    patch: {
      requestBody: { content: {
        "application/json": {
          chargeDate?: string;
          mileage?: number;
          energyKwh?: number;
          pricePerKwh?: number;
          chargerType?: "home_socket" | "ac_type2" | "dc_ccs" | "dc_chademo" | "tesla_sc" | "other";
          socStartPercent?: number | null;
          socEndPercent?: number | null;
          stationName?: string | null;
          isFullCharge?: boolean;
        };
      } };
      responses: {
        200: { content: {
          "application/json": {
            id: string;
            vehicleId: string;
            chargeDate: string;
            mileage: number;
            energyKwh: number;
            pricePerKwh: number;
            totalCost: number;
            chargerType: string;
            socStartPercent: number | null;
            socEndPercent: number | null;
            stationName: string | null;
            isFullCharge: boolean;
            createdAt: string;
          };
        } };
        400: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
  "/api/dashboard/overview": {
    get: {
      responses: {
        200: { content: {
          "application/json": {
            totalVehicles: number;
            totalExpenses: number | null;
            totalFuelCost: number | null;
            avgFuelConsumption: number | null;
            currency: string;
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
  "/api/dashboard/expenses-by-category": {
    get: {
      responses: {
        200: { content: {
          "application/json": {
            items: ({
              category: "fuel" | "electricity" | "service" | "parts" | "insurance" | "inspection" | "other";
              total: number | null;
              count: number;
            })[];
            currency: string;
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
  "/api/dashboard/monthly-spend": {
    get: {
      responses: {
        200: { content: {
          "application/json": ({
            year: number;
            month: number;
            total: number | null;
            currency: string;
          })[];
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
  "/api/dashboard/upcoming-reminders": {
    get: {
      responses: {
        200: { content: {
          "application/json": ({
            id: string;
            vehicleId: string;
            title: string;
            description: string | null;
            dueDate: string | null;
            dueMileage: number | null;
            status: string;
            dueState: "overdue" | "due_soon";
            createdAt: string;
            updatedAt: string;
          })[];
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
  "/api/vehicles/{vehicleId}/expenses": {
    get: {
      responses: {
        200: { content: {
          "application/json": ({
            id: string;
            vehicleId: string;
            category: string;
            expenseDate: string;
            amount: number;
            description: string | null;
            sourceType: string;
            sourceId: string | null;
            isAutoSynced: boolean;
            createdAt: string;
            updatedAt: string;
          })[];
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    post: {
      requestBody: { content: {
        "application/json": {
          category: "fuel" | "electricity" | "service" | "parts" | "insurance" | "inspection" | "other";
          expenseDate: string;
          amount: number | null;
          description?: string | null;
        };
      } };
      responses: {
        201: { content: {
          "application/json": {
            id: string;
            vehicleId: string;
            category: string;
            expenseDate: string;
            amount: number;
            description: string | null;
            sourceType: string;
            sourceId: string | null;
            isAutoSynced: boolean;
            createdAt: string;
            updatedAt: string;
          };
        } };
        400: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
  "/api/vehicles/{vehicleId}/expenses/{id}": {
    get: {
      responses: {
        200: { content: {
          "application/json": {
            id: string;
            vehicleId: string;
            category: string;
            expenseDate: string;
            amount: number;
            description: string | null;
            sourceType: string;
            sourceId: string | null;
            isAutoSynced: boolean;
            createdAt: string;
            updatedAt: string;
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    delete: {
      responses: {
        204: { content: {

        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        409: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    patch: {
      requestBody: { content: {
        "application/json": {
          category?: "fuel" | "electricity" | "service" | "parts" | "insurance" | "inspection" | "other";
          expenseDate?: string;
          amount?: number | null;
          description?: string | null;
        };
      } };
      responses: {
        200: { content: {
          "application/json": {
            id: string;
            vehicleId: string;
            category: string;
            expenseDate: string;
            amount: number;
            description: string | null;
            sourceType: string;
            sourceId: string | null;
            isAutoSynced: boolean;
            createdAt: string;
            updatedAt: string;
          };
        } };
        400: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        409: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
  "/api/vehicles/{vehicleId}/fuel-logs": {
    get: {
      responses: {
        200: { content: {
          "application/json": ({
            id: string;
            vehicleId: string;
            fuelDate: string;
            mileage: number;
            liters: number;
            pricePerLiter: number;
            totalCost: number;
            stationName: string | null;
            isFullTank: boolean;
            consumptionHint: number | null;
            createdAt: string;
          })[];
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    post: {
      requestBody: { content: {
        "application/json": {
          fuelDate: string;
          mileage: number;
          liters: number;
          pricePerLiter: number;
          stationName?: string | null;
          isFullTank?: boolean;
        };
      } };
      responses: {
        201: { content: {
          "application/json": {
            id: string;
            vehicleId: string;
            fuelDate: string;
            mileage: number;
            liters: number;
            pricePerLiter: number;
            totalCost: number;
            stationName: string | null;
            isFullTank: boolean;
            consumptionHint: number | null;
            createdAt: string;
          };
        } };
        400: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
  "/api/vehicles/{vehicleId}/fuel-logs/{id}": {
    get: {
      responses: {
        200: { content: {
          "application/json": {
            id: string;
            vehicleId: string;
            fuelDate: string;
            mileage: number;
            liters: number;
            pricePerLiter: number;
            totalCost: number;
            stationName: string | null;
            isFullTank: boolean;
            consumptionHint: number | null;
            createdAt: string;
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    delete: {
      responses: {
        204: { content: {

        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    patch: {
      requestBody: { content: {
        "application/json": {
          fuelDate?: string;
          mileage?: number;
          liters?: number;
          pricePerLiter?: number;
          stationName?: string | null;
          isFullTank?: boolean;
        };
      } };
      responses: {
        200: { content: {
          "application/json": {
            id: string;
            vehicleId: string;
            fuelDate: string;
            mileage: number;
            liters: number;
            pricePerLiter: number;
            totalCost: number;
            stationName: string | null;
            isFullTank: boolean;
            consumptionHint: number | null;
            createdAt: string;
          };
        } };
        400: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
  "/healthz": {
    get: {
      responses: {
        200: { content: {
          "application/json": {
            status: "ok";
          };
        } };
      };
    };
  };
  "/readyz": {
    get: {
      responses: {
        200: { content: {
          "application/json": {
            status: "ok";
            db: "ok";
          };
        } };
        503: { content: {
          "application/json": {
            status: "error";
            db: "unreachable";
          };
        } };
      };
    };
  };
  "/api/vehicles/{vehicleId}/issues": {
    get: {
      responses: {
        200: { content: {
          "application/json": ({
            id: string;
            vehicleId: string;
            reportedDate: string;
            resolvedDate: string | null;
            title: string;
            description: string | null;
            status: string;
            priority: string;
            relatedServiceRecordId: string | null;
            createdAt: string;
            updatedAt: string;
          })[];
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    post: {
      requestBody: { content: {
        "application/json": {
          reportedDate: string;
          resolvedDate?: string | null;
          title: string;
          description?: string | null;
          status: "open" | "in_progress" | "resolved" | "cancelled";
          priority: "low" | "medium" | "high" | "critical";
          relatedServiceRecordId?: string | null;
        };
      } };
      responses: {
        201: { content: {
          "application/json": {
            id: string;
            vehicleId: string;
            reportedDate: string;
            resolvedDate: string | null;
            title: string;
            description: string | null;
            status: string;
            priority: string;
            relatedServiceRecordId: string | null;
            createdAt: string;
            updatedAt: string;
          };
        } };
        400: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
  "/api/vehicles/{vehicleId}/issues/{id}": {
    get: {
      responses: {
        200: { content: {
          "application/json": {
            id: string;
            vehicleId: string;
            reportedDate: string;
            resolvedDate: string | null;
            title: string;
            description: string | null;
            status: string;
            priority: string;
            relatedServiceRecordId: string | null;
            createdAt: string;
            updatedAt: string;
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    delete: {
      responses: {
        204: { content: {

        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    patch: {
      requestBody: { content: {
        "application/json": {
          reportedDate?: string;
          resolvedDate?: string | null;
          title?: string;
          description?: string | null;
          status?: "open" | "in_progress" | "resolved" | "cancelled";
          priority?: "low" | "medium" | "high" | "critical";
          relatedServiceRecordId?: string | null;
        };
      } };
      responses: {
        200: { content: {
          "application/json": {
            id: string;
            vehicleId: string;
            reportedDate: string;
            resolvedDate: string | null;
            title: string;
            description: string | null;
            status: string;
            priority: string;
            relatedServiceRecordId: string | null;
            createdAt: string;
            updatedAt: string;
          };
        } };
        400: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
  "/api/vehicles/{vehicleId}/mileage-readings": {
    get: {
      responses: {
        200: { content: {
          "application/json": ({
            id: string;
            vehicleId: string;
            readingDate: string;
            mileage: number;
            sourceType: string;
            sourceId: string | null;
            note: string | null;
            createdAt: string;
          })[];
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    post: {
      requestBody: { content: {
        "application/json": {
          readingDate: string;
          mileage: number;
          note?: string | null;
        };
      } };
      responses: {
        201: { content: {
          "application/json": {
            id: string;
            vehicleId: string;
            readingDate: string;
            mileage: number;
            sourceType: string;
            sourceId: string | null;
            note: string | null;
            createdAt: string;
          };
        } };
        400: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
  "/api/vehicles/{vehicleId}/mileage-readings/{id}": {
    get: {
      responses: {
        200: { content: {
          "application/json": {
            id: string;
            vehicleId: string;
            readingDate: string;
            mileage: number;
            sourceType: string;
            sourceId: string | null;
            note: string | null;
            createdAt: string;
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    delete: {
      responses: {
        204: { content: {

        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
  "/api/vehicles/{vehicleId}/reminders": {
    get: {
      responses: {
        200: { content: {
          "application/json": ({
            id: string;
            vehicleId: string;
            title: string;
            description: string | null;
            dueDate: string | null;
            dueMileage: number | null;
            status: string;
            dueState: "overdue" | "due_soon" | "ok";
            notifiedAt: string | null;
            createdAt: string;
            updatedAt: string;
          })[];
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    post: {
      requestBody: { content: {
        "application/json": {
          title: string;
          description?: string | null;
          dueDate?: string | null;
          dueMileage?: number | null;
          status: "pending" | "done" | "cancelled";
        };
      } };
      responses: {
        201: { content: {
          "application/json": {
            id: string;
            vehicleId: string;
            title: string;
            description: string | null;
            dueDate: string | null;
            dueMileage: number | null;
            status: string;
            dueState: "overdue" | "due_soon" | "ok";
            notifiedAt: string | null;
            createdAt: string;
            updatedAt: string;
          };
        } };
        400: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
  "/api/vehicles/{vehicleId}/reminders/{id}": {
    get: {
      responses: {
        200: { content: {
          "application/json": {
            id: string;
            vehicleId: string;
            title: string;
            description: string | null;
            dueDate: string | null;
            dueMileage: number | null;
            status: string;
            dueState: "overdue" | "due_soon" | "ok";
            notifiedAt: string | null;
            createdAt: string;
            updatedAt: string;
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    delete: {
      responses: {
        204: { content: {

        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    patch: {
      requestBody: { content: {
        "application/json": {
          title?: string;
          description?: string | null;
          dueDate?: string | null;
          dueMileage?: number | null;
          status?: "pending" | "done" | "cancelled";
        };
      } };
      responses: {
        200: { content: {
          "application/json": {
            id: string;
            vehicleId: string;
            title: string;
            description: string | null;
            dueDate: string | null;
            dueMileage: number | null;
            status: string;
            dueState: "overdue" | "due_soon" | "ok";
            notifiedAt: string | null;
            createdAt: string;
            updatedAt: string;
          };
        } };
        400: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
  "/api/vehicles/{vehicleId}/service-records": {
    get: {
      responses: {
        200: { content: {
          "application/json": ({
            id: string;
            vehicleId: string;
            serviceDate: string;
            mileage: number;
            title: string;
            description: string | null;
            laborCost: number;
            totalCost: number;
            workshopName: string | null;
            parts: ({
              id: string;
              serviceRecordId: string;
              partId: string;
              name: string;
              manufacturer: string | null;
              partNumber: string | null;
              quantity: number;
              unitPrice: number;
              totalPrice: number | null;
            })[];
            createdAt: string;
            updatedAt: string;
          })[];
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    post: {
      requestBody: { content: {
        "application/json": {
          serviceDate: string;
          mileage: number;
          title: string;
          description?: string | null;
          laborCost?: number | null;
          workshopName?: string | null;
          parts?: ({
            name: string;
            manufacturer?: string | null;
            partNumber?: string | null;
            quantity?: number;
            unitPrice: number;
          })[];
        };
      } };
      responses: {
        201: { content: {
          "application/json": {
            id: string;
            vehicleId: string;
            serviceDate: string;
            mileage: number;
            title: string;
            description: string | null;
            laborCost: number;
            totalCost: number;
            workshopName: string | null;
            parts: ({
              id: string;
              serviceRecordId: string;
              partId: string;
              name: string;
              manufacturer: string | null;
              partNumber: string | null;
              quantity: number;
              unitPrice: number;
              totalPrice: number | null;
            })[];
            createdAt: string;
            updatedAt: string;
          };
        } };
        400: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        409: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
  "/api/vehicles/{vehicleId}/service-records/{id}": {
    get: {
      responses: {
        200: { content: {
          "application/json": {
            id: string;
            vehicleId: string;
            serviceDate: string;
            mileage: number;
            title: string;
            description: string | null;
            laborCost: number;
            totalCost: number;
            workshopName: string | null;
            parts: ({
              id: string;
              serviceRecordId: string;
              partId: string;
              name: string;
              manufacturer: string | null;
              partNumber: string | null;
              quantity: number;
              unitPrice: number;
              totalPrice: number | null;
            })[];
            createdAt: string;
            updatedAt: string;
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    delete: {
      responses: {
        204: { content: {

        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    patch: {
      requestBody: { content: {
        "application/json": {
          serviceDate?: string;
          mileage?: number;
          title?: string;
          description?: string | null;
          laborCost?: number | null;
          workshopName?: string | null;
        };
      } };
      responses: {
        200: { content: {
          "application/json": {
            id: string;
            vehicleId: string;
            serviceDate: string;
            mileage: number;
            title: string;
            description: string | null;
            laborCost: number;
            totalCost: number;
            workshopName: string | null;
            parts: ({
              id: string;
              serviceRecordId: string;
              partId: string;
              name: string;
              manufacturer: string | null;
              partNumber: string | null;
              quantity: number;
              unitPrice: number;
              totalPrice: number | null;
            })[];
            createdAt: string;
            updatedAt: string;
          };
        } };
        400: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
  "/api/vehicles": {
    get: {
      responses: {
        200: { content: {
          "application/json": ({
            id: string;
            brand: string;
            model: string;
            generation?: string | null;
            productionYear: number;
            engine?: string | null;
            fuelType: "petrol" | "diesel" | "hybrid" | "electric" | "lpg" | "other";
            vin?: string | null;
            registrationNumber?: string | null;
            currentMileage: number;
            currencyCode: string;
            createdAt: string;
            updatedAt: string;
          })[];
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    post: {
      requestBody: { content: {
        "application/json": {
          brand: string;
          model: string;
          generation?: string | null;
          productionYear: number;
          engine?: string | null;
          fuelType: "petrol" | "diesel" | "hybrid" | "electric" | "lpg" | "other";
          vin?: string | null;
          registrationNumber?: string | null;
          currencyCode?: string;
        };
      } };
      responses: {
        201: { content: {
          "application/json": {
            id: string;
            brand: string;
            model: string;
            generation?: string | null;
            productionYear: number;
            engine?: string | null;
            fuelType: "petrol" | "diesel" | "hybrid" | "electric" | "lpg" | "other";
            vin?: string | null;
            registrationNumber?: string | null;
            currentMileage: number;
            currencyCode: string;
            createdAt: string;
            updatedAt: string;
          };
        } };
        400: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        409: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
  "/api/vehicles/{id}": {
    get: {
      responses: {
        200: { content: {
          "application/json": {
            id: string;
            brand: string;
            model: string;
            generation?: string | null;
            productionYear: number;
            engine?: string | null;
            fuelType: "petrol" | "diesel" | "hybrid" | "electric" | "lpg" | "other";
            vin?: string | null;
            registrationNumber?: string | null;
            currentMileage: number;
            currencyCode: string;
            createdAt: string;
            updatedAt: string;
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    delete: {
      responses: {
        204: { content: {

        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
    patch: {
      requestBody: { content: {
        "application/json": {
          brand?: string;
          model?: string;
          generation?: string | null;
          productionYear?: number;
          engine?: string | null;
          fuelType?: "petrol" | "diesel" | "hybrid" | "electric" | "lpg" | "other";
          vin?: string | null;
          registrationNumber?: string | null;
          currencyCode?: string;
        };
      } };
      responses: {
        200: { content: {
          "application/json": {
            id: string;
            brand: string;
            model: string;
            generation?: string | null;
            productionYear: number;
            engine?: string | null;
            fuelType: "petrol" | "diesel" | "hybrid" | "electric" | "lpg" | "other";
            vin?: string | null;
            registrationNumber?: string | null;
            currentMileage: number;
            currencyCode: string;
            createdAt: string;
            updatedAt: string;
          };
        } };
        400: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        401: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        404: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
        409: { content: {
          "application/json": {
            code: string;
            message: string;
            issues?: ({
              code: string;
              path: (string | number)[];
              message: string;
            })[];
          };
        } };
      };
    };
  };
}

export interface components {
  "schemas": {

  };
  "parameters": {

  };
}
